server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Opção 1: Repositório Git (recomendado)
          uri: https://github.com/klaillton/config-repo.git
          default-label: main
          search-paths: '{application}'